### ISSUE TITLE
ValueError: Variable Net_Dis/Conv/weights already exists, disallowed. Did you mean to set reuse=True in VarScope?

### ISSUE THREAD

**Issue by CassieMai** [ChunyuanLI/Semi_Supervised_GAN#1]
Hello, @ChunyuanLI. There is an error when I ran train_cifar_feature_matching_tf.py. I think it is because variable name exists after one iteration of training discriminator. Should variables be set to 'reuse'? Do you have idea?

```
Namespace(batch_size=100, count=400, data_dir='/home/Documents/Semi_Supervised_GAN/cifar-10-python', learning_rate=0.0003, seed=1, seed_data=1, unlabeled_weight=1.0)
>> Downloading cifar-10-python.tar.gz 100.0%()
('Successfully downloaded', 'cifar-10-python.tar.gz', 170498071, 'bytes.')
Traceback (most recent call last):
  File "train_cifar_feature_matching_tf.py", line 143, in <module>
    output_before_softmax_unl, xx_unl = discriminator(x_unl, label_size)
  File "train_cifar_feature_matching_tf.py", line 93, in discriminator
    xx = layers.convolution2d(xx, 96, kernel_size=(3,3), stride=(1, 1), padding='same', activation_fn=None)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1027, in convolution
    outputs = layer.apply(inputs)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 503, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 443, in __call__
    self.build(input_shapes[0])
  File "/home/.local/lib/python2.7/site-packages/tensorflow/python/layers/convolutional.py", line 137, in build
    dtype=self.dtype)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 383, in add_variable
    trainable=trainable and self.trainable)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1065, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 962, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 360, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1561, in layer_variable_getter
    return _model_variable_getter(getter, *args, **kwargs)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1553, in _model_variable_getter
    custom_getter=getter, use_resource=use_resource)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 261, in model_variable
    use_resource=use_resource)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 216, in variable
    use_resource=use_resource)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 352, in _true_getter
    use_resource=use_resource)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 664, in _get_single_variable
    name, "".join(traceback.format_list(tb))))
ValueError: Variable Net_Dis/Conv/weights already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "/home/.local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 216, in variable
    use_resource=use_resource)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 261, in model_variable
    use_resource=use_resource)
```

**Comment by Sleepychord** [comment]
Use tensorflow=1.0.0. But I found this code can not reach the accuracy in the paper(80% this code while 99% in the paper). And my own code get similar results too. What is the essential factor?

**Comment by deeplimbo** [comment]
Hi @Sleepychord , I am running the same code and my test accuracy is stuck at 60%. Do you have this problem?

However, in the paper for Cifar10, they have an error rate of 18%.

**Comment by Sleepychord** [comment]
Hi @deeplimbo , the semi-supervised gan seems very tricky to train, every little changes might result in disastrous degradation. I just run the mnist version in this repo and can not get expected result... You can go to my repo https://github.com/Sleepychord/ImprovedGAN-pytorch to see a pytorch version on Mnist.

**Comment by deeplimbo** [comment]
Hi @Sleepychord , thanks for your reply. I am not so familiar with PyTorch but will try to translate.

I hope you're getting 80% accuracy for MNIST. I ran Cifar10 and with 400 labelled samples per class this code reaches an accuracy of 67%, which is way below than the paper.
